In [21]:
import pandas as pd
data = pd.read_csv('/Users/himanshuaggarwal/ironhack/himanshu/data/vehicles/vehicles.csv')
data.head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [22]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Displacement', 'Cylinders',
       'Transmission', 'Drivetrain', 'Vehicle Class', 'Fuel Type',
       'Fuel Barrels/Year', 'City MPG', 'Highway MPG', 'Combined MPG',
       'CO2 Emission Grams/Mile', 'Fuel Cost/Year'],
      dtype='object')

In [24]:
data.columns = ['Manufacturer','Model','Year','Displacement',
                'Cylinders','Transmission','Drivetrain',
                'Vehicle Class','Fuel Type','Fuel Barrels/Year',
                'City MPG','Highway MPG','Combined MPG',
                'CO2 Emission Grams/Mile','Fuel Cost/Year']

In [25]:
data.head(5)

,Manufacturer,Model,Year,Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

In [29]:
data = data.rename(columns={'Manufacturer':'Make',
                            'Displacement':'Engine Displacement'})

In [31]:
column_order = ['Year','Make','Model','Vehicle Class',
                'Transmission','Drivetrain','Fuel Type',
                'Cylinders','Engine Displacement','Fuel Barrels/Year',
                'City MPG','Highway MPG','Combined MPG',
                'CO2 Emission Grams/Mile','Fuel Cost/Year']

data = data[column_order]

In [32]:
column_order2 = ['Year','Make','Model','Vehicle Class',
                'Transmission']

data2 = data[column_order2]
data2.head()

,Year,Make,Model,Vehicle Class,Transmission
0,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd
1,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Automatic 3-spd
2,1985,AM General,Post Office DJ5 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd
3,1985,AM General,Post Office DJ8 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd
4,1987,ASC Incorporated,GNX,Midsize Cars,Automatic 4-spd

In [33]:
data = data[column_order]
data.head()

,Year,Make,Model,Vehicle Class,Transmission,Drivetrain,Fuel Type,Cylinders,Engine Displacement,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,4.0,2.5,19.388824,18,17,17,522.764706,1950
1,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,6.0,4.2,25.354615,13,13,13,683.615385,2550
2,1985,AM General,Post Office DJ5 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,4.0,2.5,20.600625,16,17,16,555.437500,2100
3,1985,AM General,Post Office DJ8 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,6.0,4.2,25.354615,13,13,13,683.615385,2550
4,1987,ASC Incorporated,GNX,Midsize Cars,Automatic 4-spd,Rear-Wheel Drive,Premium,6.0,3.8,20.600625,14,21,16,555.437500,2550

In [34]:
filtered = data[(data['Make']=='Ford') & 
                (data['Cylinders']>=6) & 
                (data['Combined MPG'] < 18)]

filtered.head()

,Year,Make,Model,Vehicle Class,Transmission,Drivetrain,Fuel Type,Cylinders,Engine Displacement,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
11442,1986,Ford,Aerostar Van,Vans,Automatic 4-spd,Rear-Wheel Drive,Regular,6.0,2.8,19.388824,15,21,17,522.764706,1950
11450,1988,Ford,Aerostar Van,Vans,Automatic 4-spd,Rear-Wheel Drive,Regular,6.0,3.0,19.388824,15,20,17,522.764706,1950
11452,1989,Ford,Aerostar Van,Vans,Automatic 4-spd,Rear-Wheel Drive,Regular,6.0,3.0,19.388824,15,21,17,522.764706,1950
11456,1990,Ford,Aerostar Van,Vans,Automatic 4-spd,Rear-Wheel Drive,Regular,6.0,4.0,19.388824,15,20,17,522.764706,1950
11459,1991,Ford,Aerostar Van,Vans,Automatic 4-spd,Rear-Wheel Drive,Regular,6.0,4.0,19.388824,15,20,17,522.764706,1950

In [ ]:
mpg_labels = ['Very Low', 'Low', 'Moderate', 'High', 'Very High']

In [35]:
bins = pd.cut(data['Combined MPG'],5, labels=mpg_labels)
bins.head(10)

0         Low
1    Very Low
2    Very Low
3    Very Low
4    Very Low
5         Low
6         Low
7         Low
8         Low
9         Low
Name: Combined MPG, dtype: category
Categories (5, object): [Very Low < Low < Moderate < High < Very High]

In [36]:
data['Combined MPG'].head(10)

0    17
1    13
2    16
3    13
4    16
5    22
6    24
7    20
8    22
9    24
Name: Combined MPG, dtype: int64

In [37]:
pd.concat([bins,data['Combined MPG']], axis = 1).head(10)

   Combined MPG  Combined MPG
0           Low            17
1      Very Low            13
2      Very Low            16
3      Very Low            13
4      Very Low            16
5           Low            22
6           Low            24
7           Low            20
8           Low            22
9           Low            24

In [38]:
avg_mpg = data.groupby('Make', as_index=False).agg({'Combined MPG':'mean'})
avg_mpg.columns = ['Make', 'Avg_MPG']

In [39]:
avg_mpg.head(10)

                          Make    Avg_MPG
0                   AM General  14.750000
1             ASC Incorporated  16.000000
2                        Acura  21.506623
3                   Alfa Romeo  19.512195
4  American Motors Corporation  17.681818
5                 Aston Martin  13.578947
6                         Audi  20.325843
7              Aurora Cars Ltd  15.000000
8            Autokraft Limited  16.500000
9                          BMW  20.032797

In [40]:
data['Make'].head(30)

0           AM General
1           AM General
2           AM General
3           AM General
4     ASC Incorporated
5                Acura
6                Acura
7                Acura
8                Acura
9                Acura
10               Acura
11               Acura
12               Acura
13               Acura
14               Acura
15               Acura
16               Acura
17               Acura
18               Acura
19               Acura
20               Acura
21               Acura
22               Acura
23               Acura
24               Acura
25               Acura
26               Acura
27               Acura
28               Acura
29               Acura
Name: Make, dtype: object

In [41]:
data = pd.merge(data, avg_mpg, on='Make')
data.head(10)

,Year,Make,Model,Vehicle Class,Transmission,Drivetrain,Fuel Type,Cylinders,Engine Displacement,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Avg_MPG
0,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,4.0,2.5,19.388824,18,17,17,522.764706,1950,14.750000
1,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,6.0,4.2,25.354615,13,13,13,683.615385,2550,14.750000
2,1985,AM General,Post Office DJ5 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,4.0,2.5,20.600625,16,17,16,555.437500,2100,14.750000
3,1985,AM General,Post Office DJ8 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,6.0,4.2,25.354615,13,13,13,683.615385,2550,14.750000
4,1987,ASC Incorporated,GNX,Midsize Cars,Automatic 4-spd,Rear-Wheel Drive,Premium,6.0,3.8,20.600625,14,21,16,555.437500,2550,16.000000
5,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Automatic 4-spd,Front-Wheel Drive,Regular,4.0,2.2,14.982273,20,26,22,403.954545,1500,21.506623
6,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Manual 5-spd,Front-Wheel Drive,Regular,4.0,2.2,13.733750,22,28,24,370.291667,1400,21.506623
7,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Automatic 4-spd,Front-Wheel Drive,Regular,6.0,3.0,16.480500,18,26,20,444.350000,1650,21.506623
8,1998,Acura,2.3CL/3.0CL,Subcompact Cars,Automatic 4-spd,Front-Wheel Drive,Regular,4.0,2.3,14.982273,19,27,22,403.954545,1500,21.506623
9,1998,Acura,2.3CL/3.0CL,Subcompact Cars,Manual 5-spd,Front-Wheel Drive,Regular,4.0,2.3,13.733750,21,29,24,370.291667,1400,21.506623

In [ ]:
melted = pd.melt(data, id_vars=['Year','Make','Model'], 
                 value_vars=['City MPG','Highway MPG','Combined MPG'])
melted.head(300)

In [42]:
data['Transmission'].head(100)

0     Automatic 3-spd
1     Automatic 3-spd
2     Automatic 3-spd
3     Automatic 3-spd
4     Automatic 4-spd
5     Automatic 4-spd
6        Manual 5-spd
7     Automatic 4-spd
8     Automatic 4-spd
9        Manual 5-spd
10    Automatic 4-spd
11    Automatic 4-spd
12       Manual 5-spd
13    Automatic 4-spd
14    Automatic 4-spd
15    Automatic 4-spd
16    Automatic 4-spd
17    Automatic 4-spd
18    Automatic 4-spd
19    Automatic 4-spd
20    Automatic 4-spd
21     Automatic (S5)
22     Automatic (S5)
23       Manual 6-spd
24     Automatic (S5)
25    Automatic 4-spd
26    Automatic 5-spd
27     Automatic (S5)
28     Automatic (S5)
29     Automatic (S5)
           ...
70       Manual 5-spd
71    Automatic 4-spd
72       Manual 5-spd
73       Manual 5-spd
74    Automatic 4-spd
75       Manual 5-spd
76       Manual 5-spd
77    Automatic 4-spd
78       Manual 5-spd
79    Automatic 4-spd
80       Manual 5-spd
81       Manual 5-spd
82    Automatic 4-spd
83       Manual 5-spd
84       Manual 5-spd
85    Automatic 4-spd
86       Manual 5-spd
87       Manual 5-spd
88    Automatic 4-spd
89       Manual 5-spd
90       Manual 5-spd
91    Automatic 4-spd
92       Manual 5-spd
93    Automatic 4-spd
94       Manual 5-spd
95    Automatic 4-spd
96       Manual 5-spd
97    Automatic 4-spd
98       Manual 5-spd
99    Automatic 4-spd
Name: Transmission, Length: 100, dtype: object

In [ ]:
data.loc[data['Transmission'].str.startswith('A'), 'TransType'] = 'Automatic'

In [43]:
drivetrain = pd.get_dummies(data['Drivetrain'])
drivetrain.head()

,2-Wheel Drive,"2-Wheel Drive, Front",4-Wheel Drive,4-Wheel or All-Wheel Drive,All-Wheel Drive,Front-Wheel Drive,Part-time 4-Wheel Drive,Rear-Wheel Drive
0,1,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,1

In [44]:
data.head(10)

,Year,Make,Model,Vehicle Class,Transmission,Drivetrain,Fuel Type,Cylinders,Engine Displacement,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year,Avg_MPG
0,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,4.0,2.5,19.388824,18,17,17,522.764706,1950,14.750000
1,1984,AM General,FJ8c Post Office,Special Purpose Vehicle 2WD,Automatic 3-spd,2-Wheel Drive,Regular,6.0,4.2,25.354615,13,13,13,683.615385,2550,14.750000
2,1985,AM General,Post Office DJ5 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,4.0,2.5,20.600625,16,17,16,555.437500,2100,14.750000
3,1985,AM General,Post Office DJ8 2WD,Special Purpose Vehicle 2WD,Automatic 3-spd,Rear-Wheel Drive,Regular,6.0,4.2,25.354615,13,13,13,683.615385,2550,14.750000
4,1987,ASC Incorporated,GNX,Midsize Cars,Automatic 4-spd,Rear-Wheel Drive,Premium,6.0,3.8,20.600625,14,21,16,555.437500,2550,16.000000
5,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Automatic 4-spd,Front-Wheel Drive,Regular,4.0,2.2,14.982273,20,26,22,403.954545,1500,21.506623
6,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Manual 5-spd,Front-Wheel Drive,Regular,4.0,2.2,13.733750,22,28,24,370.291667,1400,21.506623
7,1997,Acura,2.2CL/3.0CL,Subcompact Cars,Automatic 4-spd,Front-Wheel Drive,Regular,6.0,3.0,16.480500,18,26,20,444.350000,1650,21.506623
8,1998,Acura,2.3CL/3.0CL,Subcompact Cars,Automatic 4-spd,Front-Wheel Drive,Regular,4.0,2.3,14.982273,19,27,22,403.954545,1500,21.506623
9,1998,Acura,2.3CL/3.0CL,Subcompact Cars,Manual 5-spd,Front-Wheel Drive,Regular,4.0,2.3,13.733750,21,29,24,370.291667,1400,21.506623

In [49]:
melted = pd.melt(data, id_vars=['Year','Make','Model'], 
                 value_vars=['City MPG','Highway MPG','Combined MPG'])
melted.head(100)

    Year              Make                Model  variable  value
0   1984        AM General    DJ Po Vehicle 2WD  City MPG     18
1   1984        AM General     FJ8c Post Office  City MPG     13
2   1985        AM General  Post Office DJ5 2WD  City MPG     16
3   1985        AM General  Post Office DJ8 2WD  City MPG     13
4   1987  ASC Incorporated                  GNX  City MPG     14
5   1997             Acura          2.2CL/3.0CL  City MPG     20
6   1997             Acura          2.2CL/3.0CL  City MPG     22
7   1997             Acura          2.2CL/3.0CL  City MPG     18
8   1998             Acura          2.3CL/3.0CL  City MPG     19
9   1998             Acura          2.3CL/3.0CL  City MPG     21
10  1998             Acura          2.3CL/3.0CL  City MPG     17
11  1999             Acura          2.3CL/3.0CL  City MPG     20
12  1999             Acura          2.3CL/3.0CL  City MPG     21
13  1999             Acura          2.3CL/3.0CL  City MPG     17
14  1995             Acura                2.5TL  City MPG     18
15  1996             Acura          2.5TL/3.2TL  City MPG     18
16  1996             Acura          2.5TL/3.2TL  City MPG     17
17  1997             Acura          2.5TL/3.2TL  City MPG     18
18  1997             Acura          2.5TL/3.2TL  City MPG     17
19  1998             Acura          2.5TL/3.2TL  City MPG     17
20  1998             Acura          2.5TL/3.2TL  City MPG     17
21  2001             Acura                3.2CL  City MPG     17
22  2002             Acura                3.2CL  City MPG     17
23  2003             Acura                3.2CL  City MPG     17
24  2003             Acura                3.2CL  City MPG     17
25  1999             Acura                3.2TL  City MPG     17
26  2000             Acura                3.2TL  City MPG     17
27  2001             Acura                3.2TL  City MPG     17
28  2002             Acura                3.2TL  City MPG     17
29  2003             Acura                3.2TL  City MPG     17
..   ...               ...                  ...       ...    ...
70  1995             Acura              Integra  City MPG     22
71  1995             Acura              Integra  City MPG     21
72  1995             Acura              Integra  City MPG     22
73  1996             Acura              Integra  City MPG     22
74  1996             Acura              Integra  City MPG     21
75  1996             Acura              Integra  City MPG     22
76  1997             Acura              Integra  City MPG     22
77  1997             Acura              Integra  City MPG     21
78  1997             Acura              Integra  City MPG     22
79  1998             Acura              Integra  City MPG     21
80  1998             Acura              Integra  City MPG     22
81  1998             Acura              Integra  City MPG     22
82  1999             Acura              Integra  City MPG     21
83  1999             Acura              Integra  City MPG     22
84  1999             Acura              Integra  City MPG     22
85  2000             Acura              Integra  City MPG     21
86  2000             Acura              Integra  City MPG     22
87  2000             Acura              Integra  City MPG     22
88  2001             Acura              Integra  City MPG     21
89  2001             Acura              Integra  City MPG     22
90  2001             Acura              Integra  City MPG     22
91  1986             Acura               Legend  City MPG     17
92  1986             Acura               Legend  City MPG     18
93  1987             Acura               Legend  City MPG     17
94  1987             Acura               Legend  City MPG     18
95  1987             Acura               Legend  City MPG     16
96  1987             Acura               Legend  City MPG     17
97  1988             Acura               Legend  City MPG     16
98  1988             Acura               Legend  City MPG     17
99  1989             Acura               Legend  City MPG     16

[100 rows x 5 columns]